name: Release library build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check-build:
    name: Check build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Pre-build devShell
        run: nix build --no-link .#devShells.$(nix eval --impure --raw --expr 'builtins.currentSystem').default
      - name: Build release libraries
        shell: 'nix develop -c bash -e {0}'
        run: make release-all
      - name: Upload release libraries
        uses: actions/upload-artifact@v4
        with:
          name: release-libraries
          path: out/
          if-no-files-found: error
